export default async function handler(req, res) {
  const { checkAndIncrementQuota } = await import('./firebase.js');

  // CORS Configuration
  res.setHeader('Access-Control-Allow-Credentials', true);
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET,OPTIONS,PATCH,DELETE,POST,PUT');
  res.setHeader(
    'Access-Control-Allow-Headers',
    'X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version'
  );

  // Handle OPTIONS request for CORS
  if (req.method === 'OPTIONS') {
    res.status(200).end();
    return;
  }

  // Only allow POST requests
  if (req.method !== 'POST') {
    res.status(405).json({ error: 'Method not allowed' });
    return;
  }

  const { resumeData, language } = req.body;

  if (!resumeData) {
    res.status(400).json({ error: 'resumeData is required' });
    return;
  }

  try {
    await checkAndIncrementQuota();
    
    const apiKey = process.env.GEMINI_API_KEY_MASTER;
    
    if (!apiKey) {
      throw new Error("GEMINI_API_KEY_MASTER is missing in environment variables");
    }

    const apiUrl = `https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite:generateContent?key=${apiKey}`;

    const targetLang = language === 'fr' ? 'French' : language === 'es' ? 'Spanish' : 'English';
    const systemPrompt = `You are a senior career coach and ATS optimization specialist who adapts advice to each individual's specific profession and industry.

STEP 1 — PROFILE IDENTIFICATION (do NOT include this in your output):
Before generating tips, silently identify the candidate's:
- Professional domain (e.g. software engineering, nursing, teaching, graphic design, marketing, finance, logistics, law, etc.)
- Career level (junior, mid, senior, executive)
- Industry context

STEP 2 — GENERATE 3 TAILORED TIPS:
Based on the identified profile, provide exactly 3 short, highly specific, actionable recommendations to improve this resume's ATS score and recruiter impact.

ABSOLUTE RULES:
1. Every tip MUST be relevant to this specific person's profession. Do NOT give generic advice that applies to everyone.
2. Do NOT recommend quantifiable metrics (percentages, dollar amounts, numbers) unless the person's profession naturally produces such metrics. For example:
   - A software engineer → yes, suggest performance metrics, latency, scale
   - A nurse or teacher → suggest impact in domain-appropriate terms (patients cared for, curricula developed, student outcomes), NOT revenue or percentages
   - A designer → suggest portfolio impact, project scope, deliverables — NOT financial KPIs
3. Do NOT suggest adding "technical skills" to non-technical profiles. Suggest skills relevant to THEIR field.
4. Analyze the ACTUAL content: read their bullet points, their summary, their skills — and react to what is truly weak or missing for their specific role.
5. Never produce templated tips like "Add metrics to your bullets" without specifying WHICH bullet and WHAT kind of metric makes sense for their job.
6. Each tip should feel like it was written by a recruiter who specializes in THEIR industry.
7. Tips MUST be in ${targetLang}.
8. CRITICAL LANGUAGE RULE: You MUST write the output tips entirely in ${targetLang}. Do NOT write them in English unless the target language is English. If the target language is French, write them in French. If the target language is Spanish, write them in Spanish.

OUTPUT FORMAT — Return ONLY this JSON:
{
  "tips": [
    "Tip 1...",
    "Tip 2...",
    "Tip 3..."
  ]
}
DO NOT include markdown code fences.`;

    const response = await fetch(apiUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [{ parts: [{ text: systemPrompt }, { text: `Resume Data:\n${JSON.stringify(resumeData)}` }] }],
        generationConfig: {
          temperature: 0.2,
          responseMimeType: "application/json"
        }
      })
    });

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      console.error('Gemini API Error:', errorData);
      
      if (response.status === 429) {
         return res.status(429).json({ error: 'QUOTA_EXCEEDED' });
      }
      
      throw new Error(`Gemini API error: ${response.status} ${response.statusText}`);
    }

    const data = await response.json();
    const generatedText = data.candidates?.[0]?.content?.parts?.[0]?.text;
    
    if (!generatedText) {
      throw new Error("No response generated by Gemini");
    }

    const jsonResponse = JSON.parse(generatedText);
    res.status(200).json(jsonResponse);

  } catch (error) {
    console.error('Analyze function error:', error);
    res.status(500).json({ error: error.message || 'Internal server error' });
  }
}
