export default async function handler(req, res) {
  const { checkAndIncrementQuota } = await import('./firebase.js');

  // CORS Configuration
  res.setHeader('Access-Control-Allow-Credentials', true);
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET,OPTIONS,PATCH,DELETE,POST,PUT');
  res.setHeader(
    'Access-Control-Allow-Headers',
    'X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version'
  );

  // Handle OPTIONS request for CORS
  if (req.method === 'OPTIONS') {
    res.status(200).end();
    return;
  }

  // Only allow POST requests
  if (req.method !== 'POST') {
    res.status(405).json({ error: 'Method not allowed' });
    return;
  }

  const { resumeData, language, jobDescription } = req.body;

  if (!resumeData) {
    res.status(400).json({ error: 'resumeData is required' });
    return;
  }

  try {
    await checkAndIncrementQuota();
    
    const apiKey = process.env.GEMINI_API_KEY_MASTER;
    
    if (!apiKey) {
      throw new Error("GEMINI_API_KEY_MASTER is missing in environment variables");
    }

    const apiUrl = `https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite:generateContent?key=${apiKey}`;

    const targetLang = language === 'fr' ? 'French' : language === 'es' ? 'Spanish' : 'English';
    const systemPrompt = `You are a senior career coach and ATS optimization specialist who adapts advice to each individual's specific profession and industry.

STEP 1 — PROFILE & JOB IDENTIFICATION:
Silently analyze the candidate's background and target job description (if provided).

STEP 2 — GENERATE 3 TAILORED, HIGH-IMPACT RECOMMENDATIONS:
Provide exactly 3 short, highly specific, actionable recommendations to improve this resume's ATS score and recruiter impact.

STEP 3 — CONCRETE PROPOSED TEXT SNIPPET FOR EACH RECOMMENDATION:
For EACH tip, you MUST generate a concrete, ready-to-use proposed text snippet ("suggestedText") tailored specifically to the candidate's actual experience and the target job requirements.
Examples of concrete suggestions:
- If recommending metrics: provide the exact rewritten bullet point with realistic metrics (e.g. "Developpement de 8+ tableaux de bord Power BI pour le suivi de 50MW d'actifs (+15% de mobilite).")
- If recommending summary optimization: provide the exact 2-3 sentence tailored summary phrase.
- If recommending skills: provide the exact list of technical skills to add.

ABSOLUTE RULES:
1. Every tip MUST be relevant to this specific person's profession.
2. "suggestedText" MUST be ready to insert directly into the resume without needing placeholders.
3. Tips and suggestedText MUST be written entirely in ${targetLang}.

OUTPUT FORMAT — Return ONLY this JSON structure:
{
  "tips": [
    {
      "title": "Short title of the recommendation",
      "description": "Explanation of why this improves the ATS match.",
      "suggestedText": "Exact concrete text snippet ready to insert into the resume.",
      "targetSection": "summary" | "experience" | "skills" | "projects",
      "targetIndex": 0,
      "action": "APPLY_SUGGESTION"
    }
  ]
}
DO NOT include markdown code fences.`;

    const response = await fetch(apiUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [{ parts: [{ text: systemPrompt }, { text: `Resume Data:\n${JSON.stringify(resumeData)}` }] }],
        generationConfig: {
          temperature: 0.2,
          responseMimeType: "application/json"
        }
      })
    });

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      console.error('Gemini API Error:', errorData);
      
      if (response.status === 429) {
         return res.status(429).json({ error: 'QUOTA_EXCEEDED' });
      }
      
      throw new Error(`Gemini API error: ${response.status} ${response.statusText}`);
    }

    const data = await response.json();
    const generatedText = data.candidates?.[0]?.content?.parts?.[0]?.text;
    
    if (!generatedText) {
      throw new Error("No response generated by Gemini");
    }

    const jsonResponse = JSON.parse(generatedText);
    res.status(200).json(jsonResponse);

  } catch (error) {
    console.error('Analyze function error:', error);
    res.status(500).json({ error: error.message || 'Internal server error' });
  }
}
