export default async function handler(req, res) {
  const { checkAndIncrementQuota } = await import('./firebase.js');

  // CORS Configuration
  res.setHeader('Access-Control-Allow-Credentials', true);
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET,OPTIONS,PATCH,DELETE,POST,PUT');
  res.setHeader(
    'Access-Control-Allow-Headers',
    'X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version'
  );

  // Handle OPTIONS request for CORS
  if (req.method === 'OPTIONS') {
    res.status(200).end();
    return;
  }

  // Only allow POST requests
  if (req.method !== 'POST') {
    res.status(405).json({ error: 'Method not allowed' });
    return;
  }

  const { resumeData, language, jobDescription } = req.body;

  if (!resumeData) {
    res.status(400).json({ error: 'resumeData is required' });
    return;
  }

  try {
    await checkAndIncrementQuota();
    
    const apiKey = process.env.GEMINI_API_KEY_MASTER;
    
    if (!apiKey) {
      throw new Error("GEMINI_API_KEY_MASTER is missing in environment variables");
    }

    const apiUrl = `https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite:generateContent?key=${apiKey}`;

    const targetLang = language === 'fr' ? 'French' : language === 'es' ? 'Spanish' : 'English';
    const systemPrompt = `You are a senior career coach and ATS optimization specialist who adapts advice to each individual's specific profession and industry.

STEP 1 — PROFILE & JOB IDENTIFICATION:
Silently analyze the candidate's background and target job description (if provided).

STEP 2 — GENERATE 3 DISTINCT, TAILORED RECOMMENDATIONS:
Generate exactly 3 DIFFERENT recommendations covering distinct areas of the resume:
1. One recommendation for Work Experience (Bullet Point with REALISTIC QUANTIFIED METRICS).
2. One recommendation for Executive Summary / Title Alignment.
3. One recommendation for Technical Skills & Hard Tools.

STEP 3 — CONCRETE, ACTIONABLE SUGGESTED TEXT:
For EACH recommendation, you MUST provide an exact, ready-to-use proposed text snippet ("suggestedText"):
- IF THE TIP IS ABOUT QUANTIFYING IMPACT OR METRICS: "targetSection" MUST BE "experience". "suggestedText" MUST be a single, high-impact bullet point CONTAINING NUMERICAL METRICS & PERCENTAGES (e.g., "Analyse des données SCADA et GMAO pour 50+ MW d'actifs photovoltaïques, réduisant le temps d'arrêt non planifié de 18% et améliorant la productivité globale de 12%.").
- IF THE TIP IS ABOUT SUMMARY: "targetSection" MUST BE "summary". "suggestedText" MUST be a 2-3 sentence summary tailored to the position.
- IF THE TIP IS ABOUT SKILLS: "targetSection" MUST BE "skills". "suggestedText" MUST be a comma-separated list of missing technical tools/skills (e.g., "SCADA, GMAO, SQL, Power BI, Python, Maintenance prédictive").

CRITICAL RULES:
1. NEVER output placeholders like [X%] or [N]. Always generate realistic, credible domain numbers based on the candidate's background (e.g., 15%, 50MW, 8+ tableaux de bord).
2. NEVER repeat the exact same suggestedText across different tips. Each tip MUST have unique, distinct proposed text.
3. If recommending metrics or quantification, NEVER return a summary paragraph. Always return a quantified work experience bullet point!
4. All text MUST be written entirely in ${targetLang}.

OUTPUT FORMAT — Return ONLY a valid JSON object matching this schema:
{
  "tips": [
    {
      "title": "Short title of recommendation",
      "description": "Why this improves ATS match",
      "suggestedText": "Exact concrete text snippet ready to insert",
      "targetSection": "experience" | "summary" | "skills" | "projects",
      "targetIndex": 0,
      "action": "APPLY_SUGGESTION"
    }
  ]
}
DO NOT include markdown code fences.`;

    const response = await fetch(apiUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [{ parts: [{ text: systemPrompt }, { text: `Resume Data:\n${JSON.stringify(resumeData)}` }] }],
        generationConfig: {
          temperature: 0.2,
          responseMimeType: "application/json"
        }
      })
    });

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      console.error('Gemini API Error:', errorData);
      
      if (response.status === 429) {
         return res.status(429).json({ error: 'QUOTA_EXCEEDED' });
      }
      
      throw new Error(`Gemini API error: ${response.status} ${response.statusText}`);
    }

    const data = await response.json();
    const generatedText = data.candidates?.[0]?.content?.parts?.[0]?.text;
    
    if (!generatedText) {
      throw new Error("No response generated by Gemini");
    }

    const jsonResponse = JSON.parse(generatedText);
    res.status(200).json(jsonResponse);

  } catch (error) {
    console.error('Analyze function error:', error);
    res.status(500).json({ error: error.message || 'Internal server error' });
  }
}
