export default async function handler(req, res) {
  const { checkAndIncrementQuota } = await import('./firebase.js');

  res.setHeader('Access-Control-Allow-Credentials', true);
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET,OPTIONS,PATCH,DELETE,POST,PUT');
  res.setHeader('Access-Control-Allow-Headers', 'X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version');

  if (req.method === 'OPTIONS') {
    res.status(200).end();
    return;
  }

  if (req.method !== 'POST') {
    res.status(405).json({ error: 'Method not allowed' });
    return;
  }

  const { resumeData } = req.body;

  if (!resumeData) {
    res.status(400).json({ error: 'resumeData is required' });
    return;
  }

  try {
    await checkAndIncrementQuota();

    const apiKey = process.env.GEMINI_API_KEY_MASTER;
    if (!apiKey) throw new Error("GEMINI_API_KEY_MASTER is missing in environment variables");

    const apiUrl = `https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite:generateContent?key=${apiKey}`;

    const cloneData = { ...resumeData };
    delete cloneData.headings;

    const systemPrompt = `Act as an expert technical recruiter and ATS optimization specialist. 
Your task is to apply AI Smart Bolding to the text values inside the provided JSON resume.

CRITICAL RULES:
1. ONLY add markdown bold (**bold text**) around the most important keywords, strong action verbs, and quantifiable metrics.
2. DO NOT change, rewrite, or translate any words. The spelling, grammar, phrasing, and punctuation of the original text must remain 100% identical. Only inject ** characters around existing words.
3. BE EXTREMELY MINIMALIST. Only bold 1-3 key terms per sentence or bullet point. Do not bold long phrases. Avoid bolding too many things.
4. DO NOT modify the JSON keys (e.g. keep "company", "title", "bullets", "summary", etc. exactly as they are).
5. Maintain all bullet point structures and JSON layout exactly identical.
6. Return ONLY a valid JSON object. Do not include markdown formatting like \`\`\`json in your response.`;

    const response = await fetch(apiUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        contents: [{ parts: [{ text: systemPrompt }, { text: `Resume Data:\n${JSON.stringify(cloneData)}` }] }],
        generationConfig: {
          temperature: 0.1,
          responseMimeType: "application/json"
        }
      })
    });

    if (!response.ok) {
      if (response.status === 429) return res.status(429).json({ error: 'QUOTA_EXCEEDED' });
      throw new Error(`Gemini API error: ${response.status}`);
    }

    const data = await response.json();
    const generatedText = data.candidates?.[0]?.content?.parts?.[0]?.text;
    
    if (!generatedText) throw new Error("No response generated by Gemini");

    const jsonResponse = JSON.parse(generatedText);
    
    if (resumeData.headings) {
      jsonResponse.headings = resumeData.headings;
    }

    res.status(200).json(jsonResponse);

  } catch (error) {
    console.error('Boldify API error:', error);
    res.status(500).json({ error: error.message || 'Internal server error' });
  }
}
