export default async function handler(req, res) {
  const { checkAndIncrementQuota } = await import('./firebase.js');

  // CORS Configuration
  res.setHeader('Access-Control-Allow-Credentials', true);
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET,OPTIONS,PATCH,DELETE,POST,PUT');
  res.setHeader(
    'Access-Control-Allow-Headers',
    'X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version'
  );

  if (req.method === 'OPTIONS') {
    res.status(200).end();
    return;
  }

  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method Not Allowed' });
  }

  try {
    const apiKey = process.env.GEMINI_API_KEY_MASTER;
    if (!apiKey) {
      throw new Error('GEMINI_API_KEY_MASTER is missing in environment variables');
    }

    await checkAndIncrementQuota();

    const { coverLetter, jobDescription } = req.body;

    if (!coverLetter) {
      return res.status(400).json({ error: 'Cover letter text is required' });
    }

    const apiUrl = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${apiKey}`;

    const systemPrompt = `You are a text formatter for cover letters. Your ONLY job is to add markdown bold markers (**) around the most impactful keywords and phrases.

ABSOLUTE RULES — VIOLATION OF ANY RULE IS A CRITICAL FAILURE:

1. TEXT PRESERVATION IS SACRED: You must NOT change, rewrite, rephrase, translate, reorder, add, or remove ANY word, punctuation, or character. The ONLY characters you may insert are ** (double asterisks) to create markdown bold.

2. WHAT TO BOLD — be strategic and selective:
   - Key action verbs that demonstrate impact (développé, piloté, optimisé, conçu, managed, led, achieved...)
   - Named technologies, tools, and methodologies (Python, Agile, SAP, Power BI...)
   - Quantifiable results and metrics (+30%, 50 collaborateurs, €2M budget...)
   - Company names and role titles when used to show relevance
   - Domain-specific terms that match the job requirements

3. BE MINIMALIST: Bold only 1-3 key terms per paragraph. Do NOT bold entire sentences or long phrases. Bold individual words or short terms only (1-3 words max per bold span). The goal is to make the recruiter's eye catch the most impressive elements at a glance.

4. PRESERVE FORMATTING: Keep all line breaks, spacing, and structure exactly as-is. Do not add or remove any whitespace or newlines.

${jobDescription ? `5. JOB RELEVANCE: Prioritize bolding terms that directly relate to the following job description:\n"""${jobDescription}"""\n` : ''}

SELF-CHECK: Strip all ** from your output. The resulting plain text MUST be character-for-character identical to the input. If not, you have an error — fix it.

Return ONLY the formatted cover letter text. No JSON, no explanation, no wrapper.`;

    const response = await fetch(apiUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        contents: [{ parts: [{ text: systemPrompt }, { text: `Cover Letter:\n${coverLetter}` }] }],
        generationConfig: {
          temperature: 0.05
        }
      })
    });

    if (!response.ok) {
      if (response.status === 429) return res.status(429).json({ error: 'QUOTA_EXCEEDED' });
      throw new Error(`Gemini API error: ${response.status}`);
    }

    const data = await response.json();
    const generatedText = data.candidates?.[0]?.content?.parts?.[0]?.text;

    if (!generatedText) throw new Error("No response generated by Gemini");

    // Validate: stripping bold markers should give back the original text
    const stripped = generatedText.replace(/\*\*/g, '');
    // Allow minor whitespace differences but check content integrity
    if (stripped.trim().length < coverLetter.trim().length * 0.8) {
      // AI truncated the text — return original with no bolding
      return res.status(200).json({ boldedCoverLetter: coverLetter });
    }

    res.status(200).json({ boldedCoverLetter: generatedText });
  } catch (error) {
    console.error('API Error (Boldify Cover Letter):', error);
    if (error.message === 'QUOTA_EXCEEDED') {
      return res.status(429).json({ error: 'QUOTA_EXCEEDED' });
    }
    res.status(500).json({ error: error.message || 'Failed to boldify cover letter' });
  }
}
