import { normalizeResumeCasing } from './_normalizeCasing.js';

export default async function handler(req, res) {
  const { checkAndIncrementQuota } = await import('./firebase.js');

  res.setHeader('Access-Control-Allow-Credentials', true);
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET,OPTIONS,PATCH,DELETE,POST,PUT');
  res.setHeader('Access-Control-Allow-Headers', 'X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version');

  if (req.method === 'OPTIONS') {
    res.status(200).end();
    return;
  }

  if (req.method !== 'POST') {
    res.status(405).json({ error: 'Method not allowed' });
    return;
  }

  const { resumeData } = req.body;

  if (!resumeData) {
    res.status(400).json({ error: 'resumeData is required' });
    return;
  }

  try {
    await checkAndIncrementQuota();

    const apiKey = process.env.GEMINI_API_KEY_MASTER;
    if (!apiKey) throw new Error("GEMINI_API_KEY_MASTER is missing in environment variables");

    const apiUrl = `https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite:generateContent?key=${apiKey}`;

    const rawClone = { ...resumeData };
    delete rawClone.headings;
    // Normalize ALL CAPS to sentence case BEFORE sending to AI
    const cloneData = normalizeResumeCasing(rawClone);

    const systemPrompt = `You are a text formatter. Your ONLY job is to add markdown bold markers (**) around important keywords in a JSON resume.

ABSOLUTE RULES — VIOLATION OF ANY RULE IS A CRITICAL FAILURE:

1. TEXT PRESERVATION IS SACRED: You must NOT change, rewrite, rephrase, translate, reorder, add, or remove ANY word, punctuation, or character. The ONLY characters you may insert are ** (double asterisks) to create markdown bold. If the original says "Wind Sector Management, Noise Regulation, Bat Protection" then your output MUST contain "**Wind Sector Management**, **Noise Regulation**, **Bat Protection**" — the exact same words with ** around them.

2. PROCESS EVERY SECTION: You MUST apply bolding to ALL experience entries, ALL project entries, ALL education entries, and the summary. Do NOT skip any section or entry. If there are 3 experience entries, all 3 must be processed.

3. WHAT TO BOLD: Bold 1-3 key terms per bullet point:
   - Strong action verbs (Développement, Conception, Analyse, Optimisation, Mise en place...)
   - Named technologies and tools (Python, Power BI, SCADA, Node.js, MongoDB, Amplitude, T-SQL...)
   - Quantifiable metrics and numbers (50MW, +15%, 8 tableaux de bord...)
   - Domain-specific named terms (Wind Sector Management, Noise Regulation, Atlas Data Federation...)

4. BE MINIMALIST: Do NOT bold entire sentences or long phrases. Bold individual words or short technical terms only (1-3 words max per bold span).

5. JSON STRUCTURE: Return the EXACT same JSON structure. Do NOT modify keys. Do NOT add or remove fields.

SELF-CHECK BEFORE RETURNING: For every bullet point, mentally strip all ** markers from your output. The resulting plain text MUST be character-for-character identical to the original input. If it is not, you have made an error — fix it.`;

    const response = await fetch(apiUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        contents: [{ parts: [{ text: systemPrompt }, { text: `Resume Data:\n${JSON.stringify(cloneData)}` }] }],
        generationConfig: {
          temperature: 0.05,
          responseMimeType: "application/json"
        }
      })
    });

    if (!response.ok) {
      if (response.status === 429) return res.status(429).json({ error: 'QUOTA_EXCEEDED' });
      throw new Error(`Gemini API error: ${response.status}`);
    }

    const data = await response.json();
    const generatedText = data.candidates?.[0]?.content?.parts?.[0]?.text;
    
    if (!generatedText) throw new Error("No response generated by Gemini");

    const jsonResponse = JSON.parse(generatedText);
    
    // --- POST-PROCESSING VALIDATION ---
    // Strip ** markers and compare against original. If text was modified, revert to original.
    const stripBold = (str) => (typeof str === 'string' ? str.replace(/\*\*/g, '') : str);
    
    // Validate and fix a string field: if stripping bold doesn't match normalized original, revert to normalized original
    const validateField = (boldedValue, normalizedOriginalValue) => {
      if (typeof boldedValue !== 'string' || typeof normalizedOriginalValue !== 'string') return normalizedOriginalValue;
      const strippedBolded = stripBold(boldedValue).trim();
      const strippedOriginal = stripBold(normalizedOriginalValue).trim();
      if (strippedBolded !== strippedOriginal) {
        // AI modified the content — revert to normalized original (no bold, but casing fixed)
        return normalizedOriginalValue;
      }
      return boldedValue;
    };

    // Validate summary
    if (jsonResponse.summary && cloneData.summary) {
      jsonResponse.summary = validateField(jsonResponse.summary, cloneData.summary);
    }

    // Validate experience bullets
    if (Array.isArray(jsonResponse.experience) && Array.isArray(cloneData.experience)) {
      for (let i = 0; i < jsonResponse.experience.length && i < cloneData.experience.length; i++) {
        const boldedExp = jsonResponse.experience[i];
        const origExp = cloneData.experience[i];
        if (boldedExp.title && origExp.title) boldedExp.title = validateField(boldedExp.title, origExp.title);
        if (boldedExp.company && origExp.company) boldedExp.company = validateField(boldedExp.company, origExp.company);
        if (Array.isArray(boldedExp.bullets) && Array.isArray(origExp.bullets)) {
          for (let j = 0; j < boldedExp.bullets.length && j < origExp.bullets.length; j++) {
            boldedExp.bullets[j] = validateField(boldedExp.bullets[j], origExp.bullets[j]);
          }
        }
        if (boldedExp.technologies && origExp.technologies) boldedExp.technologies = validateField(boldedExp.technologies, origExp.technologies);
      }
    }

    // Validate projects
    if (Array.isArray(jsonResponse.projects) && Array.isArray(cloneData.projects)) {
      for (let i = 0; i < jsonResponse.projects.length && i < cloneData.projects.length; i++) {
        const boldedProj = jsonResponse.projects[i];
        const origProj = cloneData.projects[i];
        if (boldedProj.description && origProj.description) boldedProj.description = validateField(boldedProj.description, origProj.description);
        if (Array.isArray(boldedProj.highlights) && Array.isArray(origProj.highlights)) {
          for (let j = 0; j < boldedProj.highlights.length && j < origProj.highlights.length; j++) {
            boldedProj.highlights[j] = validateField(boldedProj.highlights[j], origProj.highlights[j]);
          }
        }
      }
    }

    if (resumeData.headings) {
      jsonResponse.headings = resumeData.headings;
    }

    res.status(200).json(jsonResponse);

  } catch (error) {
    console.error('Boldify API error:', error);
    res.status(500).json({ error: error.message || 'Internal server error' });
  }
}
