export default async function handler(req, res) {
  const { checkAndIncrementQuota } = await import('./firebase.js');

  // CORS Configuration
  res.setHeader('Access-Control-Allow-Credentials', true);
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET,OPTIONS,PATCH,DELETE,POST,PUT');
  res.setHeader(
    'Access-Control-Allow-Headers',
    'X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version'
  );

  if (req.method === 'OPTIONS') {
    res.status(200).end();
    return;
  }

  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method Not Allowed' });
  }

  try {
    const apiKey = process.env.GEMINI_API_KEY_MASTER;
    if (!apiKey) {
      throw new Error('GEMINI_API_KEY_MASTER is missing in environment variables');
    }

    await checkAndIncrementQuota();

    const { data, jobDescription, language = 'en' } = req.body;

    if (!data || !jobDescription) {
      return res.status(400).json({ error: 'Resume data and job description are required' });
    }

    let resumeText = '';
    const today = new Date();
    const formattedDate = today.toLocaleDateString(
      language === 'fr' ? 'fr-FR' : language === 'es' ? 'es-ES' : 'en-US',
      { day: 'numeric', month: 'long', year: 'numeric' }
    );

    if (data.personal) {
      if (data.personal.name) resumeText += `Candidate Name: ${data.personal.name}\n`;
      if (data.personal.location) resumeText += `Address/City: ${data.personal.location}\n`;
      if (data.personal.email) resumeText += `Email: ${data.personal.email}\n`;
      if (data.personal.phone) resumeText += `Phone: ${data.personal.phone}\n`;
    }
    resumeText += `Today's Date: ${formattedDate}\n`;

    if (data.summary) resumeText += `Summary: ${data.summary}\n`;
    data.experience?.forEach(exp => {
      resumeText += `Experience: ${exp.title} at ${exp.company}\n`;
      exp.bullets?.forEach(b => { resumeText += `- ${b}\n`; });
    });
    data.education?.forEach(edu => {
      resumeText += `Education: ${edu.degree} at ${edu.institution}\n`;
    });
    if (data.skills?.technical) resumeText += `Technical Skills: ${data.skills.technical}\n`;
    if (data.skills?.soft) resumeText += `Soft Skills: ${data.skills.soft}\n`;

    const langInstruction = language === 'fr' ? 'Écris la lettre de motivation en Français.' : 
                            language === 'es' ? 'Escribe la carta de presentación en Español.' : 
                            'Write the cover letter in English.';

    const apiUrl = `https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite:generateContent?key=${apiKey}`;

    const prompt = `
You are an expert career coach and professional copywriter.
I will provide you with a Job Description and the parsed text of a candidate's Resume.
Your task is to write a highly professional, tailored, and persuasive Cover Letter for the candidate applying to this job.

Instructions:
1. Make sure to map the candidate's actual experience from their Resume to the requirements in the Job Description.
2. SENDER HEADER & DATE: Start the letter with the candidate's ACTUAL personal contact information provided below and TODAY'S DATE (${formattedDate}). NEVER use generic placeholders like '[Your Name]', '[Your Address]', '[City, State]', '[Phone Number]', '[Email Address]', or '[Date]'. Insert candidate details directly into the header block.
3. Do not invent fake experience. If the candidate lacks a specific skill, focus on their transferable skills.
4. Output ONLY the cover letter text, properly formatted using Markdown. Do not include any meta-commentary.
5. ${langInstruction}

Job Description:
"""
${jobDescription}
"""

Resume Content & Candidate Details:
"""
${resumeText}
"""
`;

    const response = await fetch(apiUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        contents: [{ parts: [{ text: prompt }] }],
        generationConfig: {
          temperature: 0.7
        }
      })
    });

    if (!response.ok) {
      if (response.status === 429) return res.status(429).json({ error: 'QUOTA_EXCEEDED' });
      throw new Error(`Gemini API error: ${response.status}`);
    }

    const result = await response.json();
    const generatedText = result.candidates?.[0]?.content?.parts?.[0]?.text;

    if (!generatedText) throw new Error("No response generated by Gemini");

    res.status(200).json({ coverLetter: generatedText });
  } catch (error) {
    console.error('API Error (Cover Letter):', error);
    if (error.message === 'QUOTA_EXCEEDED') {
      return res.status(429).json({ error: 'QUOTA_EXCEEDED' });
    }
    res.status(500).json({ error: error.message || 'Failed to generate cover letter' });
  }
}
