export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method Not Allowed' });
  }

  const apiKey = process.env.GEMINI_API_KEY_MASTER;
  if (!apiKey) {
    return res.status(500).json({ error: 'Server configuration error: Missing API Key.' });
  }

  try {
    const { sectionType, resumeContext, targetJobDescription, language } = req.body;

    if (!sectionType || !resumeContext) {
      return res.status(400).json({ error: 'Missing sectionType or resumeContext.' });
    }

    // Check minimum context
    const hasMinimum =
      resumeContext.title ||
      resumeContext.summary ||
      (resumeContext.experience && resumeContext.experience.length > 0) ||
      !!targetJobDescription?.trim();

    if (!hasMinimum) {
      return res.status(400).json({
        error: 'INSUFFICIENT_CONTEXT',
        message:
          'Please fill in at least your professional title or some work experience before using AI suggestions.',
      });
    }

    const targetLang = language === 'fr' ? 'French' : language === 'es' ? 'Spanish' : 'English';

    const systemInstruction = buildSystemPrompt(sectionType, targetLang, !!targetJobDescription);
    const promptText = buildUserPrompt(sectionType, resumeContext, targetJobDescription);

    const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`;

    const requestBody = {
      system_instruction: {
        parts: [{ text: systemInstruction }],
      },
      contents: [
        {
          role: 'user',
          parts: [{ text: promptText }],
        },
      ],
      generationConfig: {
        temperature: 0.7,
        response_mime_type: 'application/json',
      },
    };

    const { checkAndIncrementQuota } = await import('./firebase.js');
    await checkAndIncrementQuota();

    const response = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(requestBody),
    });

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      console.error('Gemini API Error:', errorData);

      if (response.status === 429) {
        return res.status(429).json({ error: 'QUOTA_EXCEEDED', message: 'Gemini API quota exceeded' });
      }
      return res.status(500).json({ error: 'INTERNAL_ERROR', message: 'Failed to call Gemini API from server' });
    }

    const data = await response.json();
    const generatedText = data.candidates?.[0]?.content?.parts?.[0]?.text;

    if (!generatedText) {
      throw new Error('No response generated by Gemini');
    }

    const suggestions = JSON.parse(generatedText);
    return res.status(200).json({ suggestions });
  } catch (error) {
    console.error('API /generateSectionContent Error:', error);

    if (error.message === 'QUOTA_EXCEEDED') {
      return res.status(429).json({
        error: 'QUOTA_EXCEEDED',
        message: 'Free server quota exceeded. Please use your own API key.',
      });
    }

    return res.status(500).json({ error: 'An error occurred while generating section content.' });
  }
}

/**
 * Builds the system prompt based on section type.
 */
function buildSystemPrompt(sectionType, targetLang, hasJobDescription) {
  const jdContext = hasJobDescription
    ? `A target Job Description is provided. You MUST align your suggestions with the requirements, keywords, and skills mentioned in this JD. This is critical for ATS optimization.`
    : `No specific job description is provided. Generate broadly relevant suggestions based on the candidate's profile and industry.`;

  const baseRules = `You are an expert career coach and resume optimization specialist.
Target language for ALL output: ${targetLang}.
${jdContext}

CRITICAL RULES:
1. NEVER invent facts, company names, or achievements that aren't supported by the candidate's profile.
2. All suggestions must be realistic, credible, and professionally relevant.
3. Base your suggestions ONLY on what can be logically inferred from the candidate's existing profile.
4. Output MUST be valid JSON matching the exact schema specified below.
5. Do NOT output markdown, backticks, or conversational text. Just raw JSON.`;

  switch (sectionType) {
    case 'tagline':
      return `${baseRules}

TASK: Suggest 3 to 5 powerful, professional titles / taglines (Titre professionnel / Slogan) for this candidate.
- If a target Job Description is provided, align the title and keywords directly with the role in the JD.
- Each title should be concise (3 to 8 words), high-impact, and accurately reflect the candidate's seniority and domain.
- Include a short subtitle or rationale explaining why this title positions them well.
- Example: { "title": "Senior Full-Stack Engineer | React & Node.js Specialist", "subtitle": "Highlights full-stack mastery and cloud scalability" }
- Output a JSON object: { "items": [{ "title": "...", "subtitle": "..." }, ...] }`;

    case 'skills_technical':
      return `${baseRules}

TASK: Suggest technical skills (hard skills) for this candidate.
- Extract skills from their experience bullet points, technologies used, and project tech stacks.
- If a Job Description is provided, include relevant keywords from it that the candidate could realistically claim.
- Do NOT suggest skills that are unrelated to the candidate's field.
- Output a JSON object: { "skills": ["skill1", "skill2", ...] }
- Suggest 8-12 skills, comma-ready (no commas inside skill names).`;

    case 'skills_soft':
      return `${baseRules}

TASK: Suggest soft skills for this candidate.
- Infer soft skills from their job titles, seniority level, and experience descriptions.
- A senior/lead role implies leadership, mentoring, strategic thinking.
- A junior role implies teamwork, adaptability, eagerness to learn.
- If a Job Description mentions soft skills, prioritize those.
- Output a JSON object: { "skills": ["skill1", "skill2", ...] }
- Suggest 5-8 soft skills.`;

    case 'skills_languages':
      return `${baseRules}

TASK: Suggest spoken languages for this candidate.
- Infer languages from: candidate name origin, location, education locations, company locations.
- Only suggest languages that are REALISTICALLY plausible for this candidate.
- Include a proficiency level for each.
- Output a JSON object: { "languages": [{ "name": "English", "level": "Native" }, ...] }
- Suggest 2-4 languages maximum.`;

    case 'certifications':
      return `${baseRules}

TASK: Suggest relevant professional certifications for this candidate.
- Base suggestions on their technical skills, industry, and experience level.
- Only suggest real, existing certifications from recognized organizations.
- If a Job Description mentions specific certifications, prioritize those.
- Output a JSON object: { "certifications": [{ "name": "Certification Name", "issuer": "Issuing Organization" }, ...] }
- Suggest 3-5 certifications.`;

    case 'custom_atouts':
      return `${baseRules}
 
TASK: Suggest professional strengths (Atouts / Key Strengths) for this candidate.
- Infer strengths from their entire profile, specifically focusing on WORK EXPERIENCE and EDUCATION, not just the tagline.
- Each strength should have a title.
- CRITICAL: The description field MUST be absolutely empty. Do not generate long text or sentences. (e.g. title: "Esprit d'analyse", description: "").
- If a Job Description is provided, align strengths with what the employer values.
- Output a JSON object: { "items": [{ "title": "Strength Name", "description": "" }, ...] }
- Suggest 4-6 strengths.`;
 
    case 'custom_loisirs':
      return `${baseRules}
 
TASK: Suggest hobbies and interests (Loisirs / Hobbies) for this candidate.
- Suggest hobbies that are credible and professionally relevant for someone in their field.
- Include a mix: one intellectual/creative, one physical/sport, one social/community.
- Avoid clichés. Be specific (e.g., "Trail running" not just "Sports").
- CRITICAL: The description field MUST be absolutely empty. NO long texts or details. (e.g. title: "Trail running", description: "").
- Output a JSON object: { "items": [{ "title": "Hobby Name", "description": "" }, ...] }
- Suggest 3-5 hobbies.`;
 
    case 'custom_langues':
      return `${baseRules}
 
TASK: Suggest spoken languages for this candidate (for a custom Languages section).
- Infer languages from: candidate name origin, location, education locations, company locations.
- Output a JSON object: { "items": [{ "title": "Language Name", "subtitle": "Proficiency Level", "description": "" }, ...] }
- CRITICAL: The subtitle should ONLY be the proficiency level (e.g. "Fluent", "Native", "Bilingual"). The description field MUST be absolutely empty. NO long texts or sentences.
- Suggest 2-4 languages.`;

    case 'custom_generic':
    default:
      return `${baseRules}

TASK: Suggest items for a custom resume section. The section name/label will be provided in the prompt.
- Generate relevant, professional content that fits the section's purpose.
- Each item should have a title, optional subtitle, and optional description.
- Output a JSON object: { "items": [{ "title": "Item Title", "subtitle": "Optional Subtitle", "description": "Optional Description" }, ...] }
- Suggest 3-5 items.`;
  }
}

/**
 * Builds the user prompt with resume context.
 */
function buildUserPrompt(sectionType, resumeContext, targetJobDescription) {
  let prompt = `### CANDIDATE PROFILE\n`;

  if (resumeContext.name) prompt += `Name: ${resumeContext.name}\n`;
  if (resumeContext.title) prompt += `Professional Title: ${resumeContext.title}\n`;
  if (resumeContext.location) prompt += `Location: ${resumeContext.location}\n`;

  if (resumeContext.summary) {
    prompt += `\nSummary: ${resumeContext.summary}\n`;
  }

  if (resumeContext.experience?.length) {
    prompt += `\n### WORK EXPERIENCE\n`;
    resumeContext.experience.forEach((exp) => {
      prompt += `- ${exp.title} at ${exp.company}`;
      if (exp.technologies) prompt += ` | Tech: ${exp.technologies}`;
      prompt += `\n`;
      if (exp.bullets?.length) {
        exp.bullets.forEach((b) => {
          prompt += `  • ${b}\n`;
        });
      }
    });
  }

  if (resumeContext.education?.length) {
    prompt += `\n### EDUCATION\n`;
    resumeContext.education.forEach((edu) => {
      prompt += `- ${edu.degree} in ${edu.field} — ${edu.institution}\n`;
    });
  }

  if (resumeContext.currentSkills) {
    prompt += `\n### CURRENT SKILLS\n`;
    if (resumeContext.currentSkills.technical)
      prompt += `Technical: ${resumeContext.currentSkills.technical}\n`;
    if (resumeContext.currentSkills.soft) prompt += `Soft: ${resumeContext.currentSkills.soft}\n`;
    if (resumeContext.currentSkills.languages)
      prompt += `Languages: ${resumeContext.currentSkills.languages}\n`;
  }

  if (resumeContext.projects?.length) {
    prompt += `\n### PROJECTS\n`;
    resumeContext.projects.forEach((p) => {
      prompt += `- ${p.name}`;
      if (p.techStack) prompt += ` (${p.techStack})`;
      if (p.description) prompt += `: ${p.description}`;
      prompt += `\n`;
    });
  }

  if (resumeContext.certifications?.length) {
    prompt += `\n### EXISTING CERTIFICATIONS\n`;
    resumeContext.certifications.forEach((c) => {
      prompt += `- ${c}\n`;
    });
  }

  if (resumeContext.customSections?.length) {
    prompt += `\n### CUSTOM SECTIONS\n`;
    resumeContext.customSections.forEach((s) => {
      prompt += `Section "${s.label}": ${s.items.join(', ') || '(empty)'}\n`;
    });
  }

  if (targetJobDescription) {
    prompt += `\n### TARGET JOB DESCRIPTION\n${targetJobDescription}\n`;
  }

  // Add section-specific label for generic custom sections
  if (sectionType === 'custom_generic' && resumeContext._customSectionLabel) {
    prompt += `\n### SECTION TO FILL\nSection Name: "${resumeContext._customSectionLabel}"\n`;
  }

  prompt += `\nGenerate suggestions now:`;

  return prompt;
}
