export default async function handler(req, res) {
  const { checkAndIncrementQuota } = await import('./firebase.js');

  res.setHeader('Access-Control-Allow-Credentials', true);
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET,OPTIONS,PATCH,DELETE,POST,PUT');
  res.setHeader('Access-Control-Allow-Headers', 'X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version');

  if (req.method === 'OPTIONS') {
    res.status(200).end();
    return;
  }

  if (req.method !== 'POST') {
    res.status(405).json({ error: 'Method not allowed' });
    return;
  }

  const { jobTitle, location, keywords, remoteOnly } = req.body;

  if (!jobTitle) {
    res.status(400).json({ error: 'jobTitle is required' });
    return;
  }

  try {
    await checkAndIncrementQuota();

    const apiKey = process.env.GEMINI_API_KEY_MASTER;
    if (!apiKey) throw new Error("GEMINI_API_KEY_MASTER is missing in environment variables");

    const apiUrl = `https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite:generateContent?key=${apiKey}`;

    const systemInstruction = `You are an expert recruitment search consultant and Google Dork engineer.
Your task is to generate a single, highly optimized, advanced Google search query (Google Dork) to find direct job offers on the web based on the user's inputs.

Guidelines for the Google Search Query:
1. It MUST target direct application pages and bypass job board aggregators. Use site exclusions or targeting like (site:lever.co OR site:greenhouse.io OR site:workable.com OR site:linkedin.com/jobs/view OR site:welcometothejungle.com) or other direct corporate job sites.
2. Group terms logically with parenthesis, AND, OR, and quotes.
3. Incorporate the required keywords intelligently. For example, if keywords is "SQL, Power BI", they must be required in the search.
4. If Remote is true, add terms like ("remote" OR "télétravail" OR "teletrabajo").
5. The output must be extremely precise, clean, and optimized.
6. CRITICAL: Return ONLY the raw search query itself. Do not wrap it in quotes (unless they are part of the search query), do not add markdown formatting, codeblocks, explanations or introductory text. Just return the search query string ready to be passed to Google.`;

    const promptText = `
### Job Search Parameters
- Job Title: ${jobTitle}
- Location: ${location || ''}
- Required Keywords: ${keywords || ''}
- Remote Only: ${remoteOnly ? 'Yes' : 'No'}
`;

    const response = await fetch(apiUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        contents: [{ parts: [{ text: systemInstruction }, { text: promptText }] }],
        generationConfig: {
          temperature: 0.1
        }
      })
    });

    if (!response.ok) {
      if (response.status === 429) return res.status(429).json({ error: 'QUOTA_EXCEEDED' });
      throw new Error(`Gemini API error: ${response.status}`);
    }

    const data = await response.json();
    const query = data.candidates?.[0]?.content?.parts?.[0]?.text;
    
    if (!query) throw new Error("No response generated by Gemini");

    res.status(200).json({ query: query.trim() });

  } catch (error) {
    console.error('Job query API error:', error);
    res.status(500).json({ error: error.message || 'Internal server error' });
  }
}
