export default async function handler(req, res) {
  const { checkAndIncrementQuota } = await import('./firebase.js');

  // CORS Configuration
  res.setHeader('Access-Control-Allow-Credentials', true);
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET,OPTIONS,PATCH,DELETE,POST,PUT');
  res.setHeader(
    'Access-Control-Allow-Headers',
    'X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version'
  );

  if (req.method === 'OPTIONS') {
    res.status(200).end();
    return;
  }

  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method Not Allowed' });
  }

  try {
    const apiKey = process.env.GEMINI_API_KEY_MASTER;
    if (!apiKey) {
      throw new Error('GEMINI_API_KEY_MASTER is missing in environment variables');
    }

    await checkAndIncrementQuota();

    const { data, jobDescription, language = 'en' } = req.body;

    if (!data || !jobDescription) {
      return res.status(400).json({ error: 'Resume data and job description are required' });
    }

    // Extract text from CV to compare — ALL sections
    let resumeText = '';
    if (data.personal?.tagline) resumeText += `Title: ${data.personal.tagline}\n`;
    if (data.summary) resumeText += `Summary: ${data.summary}\n`;
    data.experience?.forEach(exp => {
      if (exp.isSpacer) return;
      resumeText += `Title: ${exp.title} at ${exp.company}\n`;
      exp.bullets?.forEach(b => { resumeText += `- ${b}\n`; });
    });
    data.education?.forEach(edu => {
      if (edu.isSpacer) return;
      resumeText += `Education: ${edu.degree || ''} ${edu.fieldOfStudy || ''} at ${edu.institution || ''}\n`;
    });
    data.projects?.forEach(proj => {
      if (proj.isSpacer) return;
      resumeText += `Project: ${proj.name || ''}\n`;
      if (proj.description) resumeText += `${proj.description}\n`;
      proj.highlights?.forEach(h => { resumeText += `- ${h}\n`; });
    });
    data.certifications?.forEach(cert => {
      if (cert.isSpacer) return;
      resumeText += `Certification: ${cert.name || ''} - ${cert.issuer || ''}\n`;
    });
    if (data.skills?.technical) resumeText += `Technical Skills: ${data.skills.technical}\n`;
    if (data.skills?.soft) resumeText += `Soft Skills: ${data.skills.soft}\n`;
    if (data.skills?.languages) resumeText += `Languages: ${data.skills.languages}\n`;
    data.customSections?.forEach(sec => {
      resumeText += `${sec.label || 'Custom'}: `;
      sec.items?.forEach(item => {
        if (item.isSpacer) return;
        resumeText += `${item.title || ''} ${item.subtitle || ''} ${item.description || ''}, `;
      });
      resumeText += '\n';
    });

    const langInstruction = language === 'fr' ? 'Réponds en Français.' : 
                            language === 'es' ? 'Responde en Español.' : 
                            'Respond in English.';

    const apiUrl = `https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite:generateContent?key=${apiKey}`;

    const prompt = `
You are an expert ATS (Applicant Tracking System) Analyzer.
I will provide you with a Job Description and the parsed text of a candidate's Resume.

Your task is to analyze how well the Resume matches the Job Description based on keywords, skills, and qualifications.

Output a strictly valid JSON object with the following schema:
{
  "matchScore": <number between 0 and 100 representing the ATS match percentage>,
  "missingKeywords": <array of strings, listing exactly the important keywords/skills present in the Job Description but missing from the Resume>,
  "foundKeywords": <array of strings, listing the important keywords/skills that successfully matched>,
  "recommendation": <string, a short and actionable recommendation on how to improve the match score>
}

${langInstruction}

Job Description:
"""
${jobDescription}
"""

Resume Content:
"""
${resumeText}
"""
`;

    const response = await fetch(apiUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        contents: [{ parts: [{ text: prompt }] }],
        generationConfig: {
          temperature: 0.2,
          responseMimeType: "application/json"
        }
      })
    });

    if (!response.ok) {
      if (response.status === 429) return res.status(429).json({ error: 'QUOTA_EXCEEDED' });
      throw new Error(`Gemini API error: ${response.status}`);
    }

    const result = await response.json();
    const generatedText = result.candidates?.[0]?.content?.parts?.[0]?.text;
    
    if (!generatedText) throw new Error("No response generated by Gemini");

    const jsonResult = JSON.parse(generatedText);
    res.status(200).json(jsonResult);
  } catch (error) {
    console.error('API Error (ATS Keywords):', error);
    if (error.message === 'QUOTA_EXCEEDED') {
      return res.status(429).json({ error: 'QUOTA_EXCEEDED' });
    }
    res.status(500).json({ error: error.message || 'Failed to analyze keywords' });
  }
}
