export default async function handler(req, res) {
  const { checkAndIncrementQuota } = await import('./firebase.js');

  res.setHeader('Access-Control-Allow-Credentials', true);
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET,OPTIONS,PATCH,DELETE,POST,PUT');
  res.setHeader('Access-Control-Allow-Headers', 'X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version');

  if (req.method === 'OPTIONS') {
    res.status(200).end();
    return;
  }

  if (req.method !== 'POST') {
    res.status(405).json({ error: 'Method not allowed' });
    return;
  }

  const { resumeData, text, language } = req.body;

  if (!resumeData && !text) {
    res.status(400).json({ error: 'resumeData or text is required' });
    return;
  }

  try {
    await checkAndIncrementQuota();

    const apiKey = process.env.GEMINI_API_KEY_MASTER;
    if (!apiKey) throw new Error("GEMINI_API_KEY_MASTER is missing in environment variables");

    const apiUrl = `https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite:generateContent?key=${apiKey}`;
    const targetLang = language === 'fr' ? 'French' : language === 'es' ? 'Spanish' : 'English';

    if (text) {
      const systemPrompt = `Translate the following text into ${targetLang}. Keep the same tone and format, and preserve markdown bolding (**text**) or other markers. Respond ONLY with the translated text. Do not include any explanations.`;
      const response = await fetch(apiUrl, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          contents: [{ parts: [{ text: systemPrompt }, { text: `Text to translate:\n"""\n${text}\n"""` }] }],
          generationConfig: {
            temperature: 0.2
          }
        })
      });

      if (!response.ok) {
        if (response.status === 429) return res.status(429).json({ error: 'QUOTA_EXCEEDED' });
        throw new Error(`Gemini API error: ${response.status}`);
      }

      const data = await response.json();
      const generatedText = data.candidates?.[0]?.content?.parts?.[0]?.text;
      if (!generatedText) throw new Error("No response generated by Gemini");

      return res.status(200).json({ translatedText: generatedText.trim() });
    }

    const cloneData = { ...resumeData };
    delete cloneData.headings;

    const systemPrompt = `Act as an expert technical recruiter and professional translator. I am building a professional, ATS-friendly resume.
Please translate the values of the following JSON resume data into ${targetLang}. 

CRITICAL RULES:
1. ONLY translate the text values inside the JSON.
2. DO NOT translate the JSON keys (e.g. keep "company", "title", "bullets" exactly as they are).
3. Ensure the tone is professional, achievement-oriented, and uses strong action verbs.
4. Maintain all bullet point structures and do not invent new facts.
5. Keep the JSON structure exactly identical.
6. Return ONLY a valid JSON object. Do not include markdown like \`\`\`json.`;

    const response = await fetch(apiUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        contents: [{ parts: [{ text: systemPrompt }, { text: `Resume Data:\n${JSON.stringify(cloneData)}` }] }],
        generationConfig: {
          temperature: 0.2,
          responseMimeType: "application/json"
        }
      })
    });

    if (!response.ok) {
      if (response.status === 429) return res.status(429).json({ error: 'QUOTA_EXCEEDED' });
      throw new Error(`Gemini API error: ${response.status}`);
    }

    const data = await response.json();
    const generatedText = data.candidates?.[0]?.content?.parts?.[0]?.text;
    
    if (!generatedText) throw new Error("No response generated by Gemini");

    const jsonResponse = JSON.parse(generatedText);
    res.status(200).json(jsonResponse);

  } catch (error) {
    console.error('Translate API error:', error);
    res.status(500).json({ error: error.message || 'Internal server error' });
  }
}
